/**
 * Phase 7a: writes mockups/data/demo.js, the shared data every theme mock-up renders: the real `SiteView`
 * (src/shared/view) for the healthy, incident and stale fixtures, as `window.UPTELLIS_DEMO`. A script,
 * not JSON, so a mock-up opens straight from the file system. Run: bun mockups/data/generate.ts
 */
import { buildSiteView } from "../../src/shared/view";
import { fixtureInput } from "../../tests/fixtures/view";

const views = {
  healthy: buildSiteView(fixtureInput("default")),
  incident: buildSiteView(fixtureInput("incident")),
  stale: buildSiteView(fixtureInput("stale")),
};
const out = `// Generated by mockups/data/generate.ts from the synthetic fixtures. Do not edit.\nwindow.UPTELLIS_DEMO = ${JSON.stringify(views, null, 2)};\n`;
await Bun.write(new URL("./demo.js", import.meta.url).pathname, out);
console.log(`demo.js: ${Object.entries(views).map(([k, v]) => `${k} verdict=${v.verdict.state}`).join(", ")}, ${out.length} bytes`);
